# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8b220810bdc9f63bdf633f4b2ea09f37696032c6366ad5f7723590ab0347e43ad597eb72754e896f1b51684b8aaf1cf62758a224483808c8ce3acbba36325913

test:
  secret_key_base: 9edac61154b1c921f8968215e86ddb84010c0a452746fd2b767a2077b7860796999acc7c71b8aaa4465074b09af50d4c6f9463cd28b58c15d2d0072eb2465c95

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
